/**
 * Character information for story context
 */
export interface CharacterInfo {
  name: string;
  description?: string;
  role?: string; // 'protagonist', 'antagonist', 'supporting', etc.
  aliases?: string[]; // Alternative names/nicknames
}

/**
 * Story metadata for translation context
 * Provides essential information to help LLM understand the story context
 */
export interface StoryMetadata {
  /** Story ID (must match story_id in vectordb) */
  id: string;
  /** Story title */
  title: string;
  /** Author name */
  author?: string;
  /** Story category/genre */
  category?: string; // 'romance', 'fantasy', 'action', 'drama', etc.
  /** Brief story description/synopsis */
  description?: string;
  /** Main characters in the story */
  characters?: CharacterInfo[];
  /** Original language of the story */
  originalLanguage?: string;
  /** Target translation language */
  targetLanguage?: string;
  /** Additional custom metadata */
  [key: string]: unknown;
}

/**
 * Enriched context from RAG search
 */
export interface EnrichedContext {
  original_similar_paragraphs: string[];
  translated_similar_paragraphs: string[];
  relevance_scores: number[];
  generated_queries: string[];
}

/**
 * All supported research categories for translation
 */
export type ResearchCategory = 
  | 'location'      // Geographic info, landmarks, addresses
  | 'culture'       // Customs, traditions, festivals, etiquette
  | 'slang'         // Informal language, internet slang, colloquialisms
  | 'idiom'         // Proverbs, idioms, fixed expressions
  | 'trending'      // Current events, viral content, memes
  | 'knowledge'     // Technical terms, definitions, facts
  | 'season'        // Weather, climate, seasonal activities
  | 'event'         // Holidays, celebrations, historical events
  | 'food'          // Cuisine, dishes, ingredients, cooking terms
  | 'fashion'       // Clothing, traditional garments, style terms
  | 'name'          // Name meanings, transliteration, honorifics
  | 'history'       // Historical context, period-specific info
  | 'mythology'     // Folklore, legends, religious references
  | 'pop_culture'   // Movies, music, celebrities, games
  | 'dialect'       // Regional language variations
  | 'onomatopoeia'  // Sound words, exclamations
  | 'measurement'   // Units, currency, conversions
  | 'profession';   // Industry jargon, occupational terms

/**
 * Ground truth query generated by LLM
 */
export interface GroundTruthQuery {
  query: string;
  category: ResearchCategory;
  reason: string;
  /** Priority level (1-5, 1 is highest) */
  priority?: number;
  /** Suggested search language */
  searchLang?: string;
}

/**
 * Translation guidance extracted from research
 */
export interface TranslationGuidance {
  /** Terms that should be kept in original language */
  keepOriginal: string[];
  /** Suggested translations for specific terms */
  suggestedTranslations: Record<string, string>;
  /** Cultural notes for the translator */
  culturalNotes: string[];
  /** Tone/style recommendations */
  toneGuidance?: string;
}

/**
 * Ground truth context from external search (Brave Search API)
 * Provides additional context about locations, culture, slang, trending topics
 */
export interface GroundTruthContext {
  /** Original queries generated by LLM */
  queries: GroundTruthQuery[];
  /** Search results organized by category */
  results: {
    category: string;
    query: string;
    snippets: string[];
    sources?: string[];
  }[];
  /** Summarized context for translation */
  summary: string;
  /** Specific translation guidance */
  translationGuidance?: TranslationGuidance;
  /** Processing metadata */
  metadata?: {
    totalQueries: number;
    successfulSearches: number;
    processingTimeMs: number;
  };
}
